
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTOR ARROW COLON COMMA EQUAL IDENTIFIER IF LANGLE LINE LPAREN MINUS NUMBER PARAM_ARROW PARAM_ARROWL PARAM_ARROWR PARAM_GRIDX PARAM_GRIDY PARAM_HEIGHT PARAM_LINE PARAM_WIDTH PICTURE PROTOCOL RANGLE RPAREN TEXT WHILEps : PROTOCOL IDENTIFIER\n          | PROTOCOL IDENTIFIER LPAREN parameters RPAREN\n          | ps declarationdeclaration : declaration_actor\n                   | declaration_picture\n                   | declaration_drawparameter : PARAM_GRIDX EQUAL NUMBER\n                 | PARAM_GRIDY EQUAL NUMBER\n                 | PARAM_WIDTH EQUAL NUMBER\n                 | PARAM_HEIGHT EQUAL NUMBER\n                 | PARAM_LINE EQUAL IDENTIFIER\n                 | PARAM_ARROW EQUAL IDENTIFIER\n                 | PARAM_ARROWL EQUAL IDENTIFIER\n                 | PARAM_ARROWR EQUAL IDENTIFIERparameters : parameter\n                  | parameters COMMA parameterdeclaration_actor : ACTOR IDENTIFIER \n                    | ACTOR IDENTIFIER LPAREN parameters RPARENarrowpart : LANGLE\n                 | RANGLE\n                 | MINUSdeclaration_draw : IDENTIFIER COLON TEXT\n                        | IDENTIFIER LPAREN parameters RPAREN COLON TEXT\n                        | IDENTIFIER arrowpart arrowpart IDENTIFIER COLON TEXT\n                        | IDENTIFIER arrowpart arrowpart IDENTIFIER LPAREN parameters RPAREN COLON TEXTdeclaration_picture : PICTURE IDENTIFIER COLON TEXT\n                           | PICTURE IDENTIFIER LPAREN parameters RPAREN COLON TEXT'
    
_lr_action_items = {'PROTOCOL':([0,],[2,]),'$end':([1,3,4,5,6,10,11,21,48,50,51,65,66,70,72,],[0,-3,-4,-5,-6,-1,-17,-22,-26,-2,-18,-23,-24,-27,-25,]),'ACTOR':([1,3,4,5,6,10,11,21,48,50,51,65,66,70,72,],[7,-3,-4,-5,-6,-1,-17,-22,-26,-2,-18,-23,-24,-27,-25,]),'PICTURE':([1,3,4,5,6,10,11,21,48,50,51,65,66,70,72,],[9,-3,-4,-5,-6,-1,-17,-22,-26,-2,-18,-23,-24,-27,-25,]),'IDENTIFIER':([1,2,3,4,5,6,7,9,10,11,15,16,17,21,32,43,44,45,46,48,50,51,65,66,70,72,],[8,10,-3,-4,-5,-6,11,18,-1,-17,-19,-20,-21,-22,47,58,59,60,61,-26,-2,-18,-23,-24,-27,-25,]),'COLON':([8,18,37,47,64,69,],[12,33,52,62,68,71,]),'LPAREN':([8,10,11,18,47,],[13,19,20,34,63,]),'LANGLE':([8,14,15,16,17,],[15,15,-19,-20,-21,]),'RANGLE':([8,14,15,16,17,],[16,16,-19,-20,-21,]),'MINUS':([8,14,15,16,17,],[17,17,-19,-20,-21,]),'TEXT':([12,33,52,62,68,71,],[21,48,65,66,70,72,]),'PARAM_GRIDX':([13,19,20,34,38,63,],[24,24,24,24,24,24,]),'PARAM_GRIDY':([13,19,20,34,38,63,],[25,25,25,25,25,25,]),'PARAM_WIDTH':([13,19,20,34,38,63,],[26,26,26,26,26,26,]),'PARAM_HEIGHT':([13,19,20,34,38,63,],[27,27,27,27,27,27,]),'PARAM_LINE':([13,19,20,34,38,63,],[28,28,28,28,28,28,]),'PARAM_ARROW':([13,19,20,34,38,63,],[29,29,29,29,29,29,]),'PARAM_ARROWL':([13,19,20,34,38,63,],[30,30,30,30,30,30,]),'PARAM_ARROWR':([13,19,20,34,38,63,],[31,31,31,31,31,31,]),'RPAREN':([22,23,35,36,49,53,54,55,56,57,58,59,60,61,67,],[37,-15,50,51,64,-16,-7,-8,-9,-10,-11,-12,-13,-14,69,]),'COMMA':([22,23,35,36,49,53,54,55,56,57,58,59,60,61,67,],[38,-15,38,38,38,-16,-7,-8,-9,-10,-11,-12,-13,-14,38,]),'EQUAL':([24,25,26,27,28,29,30,31,],[39,40,41,42,43,44,45,46,]),'NUMBER':([39,40,41,42,],[54,55,56,57,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ps':([0,],[1,]),'declaration':([1,],[3,]),'declaration_actor':([1,],[4,]),'declaration_picture':([1,],[5,]),'declaration_draw':([1,],[6,]),'arrowpart':([8,14,],[14,32,]),'parameters':([13,19,20,34,63,],[22,35,36,49,67,]),'parameter':([13,19,20,34,38,63,],[23,23,23,23,53,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ps","S'",1,None,None,None),
  ('ps -> PROTOCOL IDENTIFIER','ps',2,'p_ps','parser.py',58),
  ('ps -> PROTOCOL IDENTIFIER LPAREN parameters RPAREN','ps',5,'p_ps','parser.py',59),
  ('ps -> ps declaration','ps',2,'p_ps','parser.py',60),
  ('declaration -> declaration_actor','declaration',1,'p_declaration','parser.py',72),
  ('declaration -> declaration_picture','declaration',1,'p_declaration','parser.py',73),
  ('declaration -> declaration_draw','declaration',1,'p_declaration','parser.py',74),
  ('parameter -> PARAM_GRIDX EQUAL NUMBER','parameter',3,'p_parameter','parser.py',79),
  ('parameter -> PARAM_GRIDY EQUAL NUMBER','parameter',3,'p_parameter','parser.py',80),
  ('parameter -> PARAM_WIDTH EQUAL NUMBER','parameter',3,'p_parameter','parser.py',81),
  ('parameter -> PARAM_HEIGHT EQUAL NUMBER','parameter',3,'p_parameter','parser.py',82),
  ('parameter -> PARAM_LINE EQUAL IDENTIFIER','parameter',3,'p_parameter','parser.py',83),
  ('parameter -> PARAM_ARROW EQUAL IDENTIFIER','parameter',3,'p_parameter','parser.py',84),
  ('parameter -> PARAM_ARROWL EQUAL IDENTIFIER','parameter',3,'p_parameter','parser.py',85),
  ('parameter -> PARAM_ARROWR EQUAL IDENTIFIER','parameter',3,'p_parameter','parser.py',86),
  ('parameters -> parameter','parameters',1,'p_parameters','parser.py',91),
  ('parameters -> parameters COMMA parameter','parameters',3,'p_parameters','parser.py',92),
  ('declaration_actor -> ACTOR IDENTIFIER','declaration_actor',2,'p_declaration_actor','parser.py',100),
  ('declaration_actor -> ACTOR IDENTIFIER LPAREN parameters RPAREN','declaration_actor',5,'p_declaration_actor','parser.py',101),
  ('arrowpart -> LANGLE','arrowpart',1,'p_arrowpart','parser.py',109),
  ('arrowpart -> RANGLE','arrowpart',1,'p_arrowpart','parser.py',110),
  ('arrowpart -> MINUS','arrowpart',1,'p_arrowpart','parser.py',111),
  ('declaration_draw -> IDENTIFIER COLON TEXT','declaration_draw',3,'p_declaration_draw','parser.py',116),
  ('declaration_draw -> IDENTIFIER LPAREN parameters RPAREN COLON TEXT','declaration_draw',6,'p_declaration_draw','parser.py',117),
  ('declaration_draw -> IDENTIFIER arrowpart arrowpart IDENTIFIER COLON TEXT','declaration_draw',6,'p_declaration_draw','parser.py',118),
  ('declaration_draw -> IDENTIFIER arrowpart arrowpart IDENTIFIER LPAREN parameters RPAREN COLON TEXT','declaration_draw',9,'p_declaration_draw','parser.py',119),
  ('declaration_picture -> PICTURE IDENTIFIER COLON TEXT','declaration_picture',4,'p_declaration_pickture','parser.py',131),
  ('declaration_picture -> PICTURE IDENTIFIER LPAREN parameters RPAREN COLON TEXT','declaration_picture',7,'p_declaration_pickture','parser.py',132),
]
